events {}

http {

    server {

        listen 80;

        location /api/products {
            proxy_pass http://product-service:4001;
        }

        location /api/orders {
            proxy_pass http://order-service:4002;
        }

        location /api/auth {
            proxy_pass http://order-service:4002;
        }
    }
}